version: 0.0
os: linux
files:
  - source:  /
    destination: /usr/share/nginx/html/practice/build/
hooks:
  AfterInstall:
    - location: Scripts/restart_nginx.sh
      timeout: 300
      runas: root
