# This is a basic workflow to help you get started with Actions

name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [12.16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm install
        run: npm install

      - name: Build
        run: npm run build
      - name: Copy file
        # You may pin to the exact commit or the version.
        # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
        uses: canastro/copy-action@0.0.2
        with:
          # Source file
          source: appspec.yml
          # Target file
          target: build/appspec.yml
    
      - name: Easy Zip Files
        # You may pin to the exact commit or the version.
        # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
        uses: vimtor/action-zip@v1
        with:
          # Files or directories to zip
          files: build
          # Name of output zip file
          dest: artifact/build.zip
          # Whether to add subdirectories to simply zip all files to the root
          recursive: true

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ec2-deploy-nginx
          AWS_ACCESS_KEY_ID: ${{ secrets. AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          SOURCE_DIR: 'artifact'
          

      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
           --application-name ec2-deploy-nginx \
           --deployment-config-name CodeDeployDefault.OneAtATime \
           --deployment-group-name ec2-deploy-practice \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=us-east-2,key=build.zip,bundleType=zip \
